spring:
  datasource:
    url: jdbc:mysql://iry8sa7tuek7n9d0:sbdplhx9tqzueabw@hwr4wkxs079mtb19.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/irn2gccor07271qy?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: iry8sa7tuek7n9d0
    password: sbdplhx9tqzueabw
    driver-class-name: com.mysql.cj.jdbc.Driver


